courierOperationManagementSystems/BranchesInfo/urls.py
from django.urls import path
from . import views

app_name = 'BranchesInfo'
urlpatterns = [
    path('branch_login_form/', views.branch_login_form, name='branch_login_form'),
    path('branch_head_dashboard/', views.branch_head_dashboard, name='branch_head_dashboard'),
    path('delivery_boy_dashboard/', views.delivery_boy_dashboard, name='delivery_boy_dashboard'),
    path('add_delivery_boy/', views.add_delivery_boy, name='add_delivery_boy'),
    path('packet_assignment_details/', views.packet_assignment_details, name='packet_assignment_details'),
    path('delete_order/<str:awbno>/', views.delete_order, name='delete_order'),
    path('update_packet_status/', views.update_packet_status, name='update_packet_status'), 
    path('generate-qr/', views.generate_and_store_qr, name='generate_and_store_qr'),
    path('logout_view/', views.logout_view, name='logout_view'),
]

courierOperationManagementSystems/administration/urls.py
from django.urls import path, include
from . import views

app_name = 'administration'

urlpatterns = [
    path('admin_login_form/', views.admin_login_form, name='admin_login_form'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('add_branch/', views.add_branch, name='add_branch'),
    path('charge_details_view/', views.charge_details_view, name='charge_details_view'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('edit_branch/<int:branch_id>/', views.edit_branch, name='edit_branch'),
    path('delete_branch/<int:branch_id>/', views.delete_branch, name='delete_branch'),
    path('edit_charge_detail/<int:charge_id>/', views.edit_charge_detail, name='edit_charge_detail'),
    path('delete_charge_detail/<int:charge_id>/', views.delete_charge_detail, name='delete_charge_detail'),
    path('add_branch_head/', views.add_branch_head, name='add_branch_head'),
]

courierOperationManagementSystems/courierOperationManagementSystems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'courierOperationManagementSystems'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(('homeapp.homeappurls','homeapp'), namespace='homeapp')),
    path("administration/", include(('administration.urls','administration'), namespace='administration')),
    path("userManagement/", include(('userManagement.urls','userManagement'), namespace='userManagement')),
    path("BranchesInfo/", include(('BranchesInfo.urls','BranchesInfo'), namespace='BranchesInfo')),
    path("packetTrackingSystem", include(('packetTrackingSystem.urls','packetTrackingSystem'), namespace='packetTrackingSystem')),
    path('captcha/', include('captcha.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courierOperationManagementSystems/userManagement/urls.py
from django.urls import path, include
from . import views

app_name = 'userManagement'

urlpatterns = [
    path('user_login_form/', views.user_login_form, name='user_login_form'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('signup/', views.signup, name='signup'),
    path('client_order/', views.client_order, name='client_order'),
    path('calculate-distance/', views.calculate_distance_view, name='calculate_distance'),
    path('profile/', views.profile_management, name='profile_management'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('feedback/', views.feedback, name='feedback'),
]

courierOperationManagementSystems/BranchesInfo/forms.py
from django import forms
from .models import Data_Records, delivery_Boy_details

class PacketAssignmentForm(forms.Form):
    awbno = forms.ModelChoiceField(queryset=Data_Records.objects.all(), empty_label=None)
    delivery_boy = forms.ModelChoiceField(queryset=delivery_Boy_details.objects.all(), empty_label=None)

courierOperationManagementSystems/BranchesInfo/views.py
from django.shortcuts import render, redirect
from .models import Branch_head, delivery_Boy_details, Data_Records, Branches, PacketAssignmentDetails
from django.contrib import messages
from django.views.decorators.cache import cache_control
from django.contrib.auth import logout
from django.urls import reverse
from django.db.models import Count
from django.utils import timezone
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404 
from .forms import PacketAssignmentForm
from .models import PacketAssignmentDetails
from packetTrackingSystem.models import Live_Updates
from django.http import JsonResponse
import qrcode
from io import BytesIO
from django.core.files import File
from django.contrib import messages
from django.shortcuts import redirect
from .models import Qr_Details, Data_Records
from django.conf import settings
import os
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from homeapp.models import Feedback


# Create your views here.
def branch_login_form(request):
    if request.method == "POST":
        userid = request.POST.get('userid')
        password = request.POST.get('password')
        user_type = request.POST.get('User_Type')
        
        
        if not user_type:
            messages.error(request, 'Please select a user type.')
            return render(request, "branch_login_form.html")
        
        if user_type == 'delivery_boy':
            
            delivery_boy = delivery_Boy_details.objects.filter(Delivery_Boy_Username=userid, Delivery_Boy_Password=password).first()
            if delivery_boy:
                request.session['Delivery_Boy_Id'] = delivery_boy.Delivery_Boy_Id
                request.session['userid'] = delivery_boy.Delivery_Boy_Username
                print("Session keys 'Delivery_Boy_Id' and 'delivery boy name' set successfully: ", delivery_boy.Delivery_Boy_Id, delivery_boy.Delivery_Boy_Username)
                return redirect(reverse('BranchesInfo:delivery_boy_dashboard') + f'?username={delivery_boy.Delivery_Boy_Username}')
            else:
                messages.error(request, 'Invalid delivery boy credentials.')
        
        elif user_type == 'branch_head':
            
            branch_head = Branch_head.objects.filter(Branch_head_Username=userid, Branch_head_Password=password).first()
            if branch_head:
                request.session['Branch_head_Id'] = branch_head.Branch_head_Id
                request.session['userid'] = branch_head.Branch_head_Username
                print("Session keys 'Branch_head_Id' and 'branch head name' set successfully: ", branch_head.Branch_head_Id, branch_head.Branch_head_Username)
                return redirect(reverse('BranchesInfo:branch_head_dashboard') + f'?username={branch_head.Branch_head_Username}')
            else:
                messages.error(request, 'Invalid branch head credentials.')
        
        
        messages.error(request, 'Invalid User or User Type')
    
    return render(request, "branch_login_form.html")

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def branch_head_dashboard(request):
    username = request.GET.get('username')
    if username:
        try:
            session_id = request.session.get('Branch_head_Id')
            if session_id is not None:
                print("Session ID of the branch head from dashboard function:", session_id)
                branch_head = Branch_head.objects.get(Branch_head_Username=username)
                branch_cd = branch_head.Branch_CD
                
                try:
                    branch = Branches.objects.get(Branch_CD=branch_cd)
                    branch_city = branch.city
                    
                    matching_orders = Data_Records.objects.filter(Sender_City=branch_city)
                    
                    awbno_list = [order.AWBNO for order in matching_orders]
                    matching_live_updates = Live_Updates.objects.filter(AWBNO__in=awbno_list)
                    
                    delivery_boys = delivery_Boy_details.objects.all()
                    assigned_orders = PacketAssignmentDetails.objects.all().order_by('-Assign_DT')
                    branches = Branches.objects.filter(Branch_CD=branch_cd)
                    branch_name = branch.Branch_NM
                    feedback_data = Feedback.objects.filter(Branch_name=branch_name)
                    return render(request, 'branch_head_dashboard.html', {'username': username, 'orders': matching_orders, 'delivery_boys': delivery_boys, 'assigned_orders': assigned_orders, 'branches': branches, 'matching_live_updates': matching_live_updates, 'feedback_data': feedback_data})
                
                except Branches.DoesNotExist:
                    print("Branches matching query does not exist for Branch_CD:", branch_cd)
                    return HttpResponse("Your Branch is deleted by The Admin Contact to the Admin to recreate your Branch to reassign you new Branch.") 
        except KeyError:
            print("Session key not found")
    return redirect(reverse('BranchesInfo:branch_login_form')) 


def delete_order(request, awbno):
    if request.method == 'POST':
        try:
            order = Data_Records.objects.get(AWBNO=awbno)
            order.delete()
            username = request.GET.get('username')
            return redirect(reverse('BranchesInfo:branch_head_dashboard') + '?username=' + username)
        except Data_Records.DoesNotExist:
            return HttpResponseNotFound("Order does not exist")
    else:
        return HttpResponseNotFound("Method not allowed")

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def delivery_boy_dashboard(request):
    
    username = request.GET.get('username')
    
    if username:
        try:
            session_id = request.session.get('Delivery_Boy_Id')
            if session_id is not None:
                print("Session ID of the delivery boy:", session_id)
                delivery_boy = delivery_Boy_details.objects.get(Delivery_Boy_Username=username)
                packets_allotted = PacketAssignmentDetails.objects.filter(Delivery_Boy_Id=session_id)
                live_track = Live_Updates.objects.filter(Delivery_Boy_Name=username)
                packets_details = []
                qr_images = {}
                for packet in packets_allotted:
                    try:
                        qr_detail = Qr_Details.objects.get(awbno=packet.AWBNO)
                        qr_images[packet.AWBNO] = qr_detail.Qr_image.url
                    except Qr_Details.DoesNotExist:
                        qr_images[packet.AWBNO] = None
                for packet in packets_allotted:
                    packet_details = Data_Records.objects.get(AWBNO=packet.AWBNO)
                    packets_details.append(packet_details)
                live_details =[]
                for live in live_track:
                    live_details = {
                        'AWBNO': live.AWBNO,
                        'transit_status': live.transit_status,
                        'update_location': live.update_location,
                        'last_update_time': live.last_update_time,
                    }
                return render(request, 'delivery_boy_dashboard.html', {'username': username, 'delivery_boy': delivery_boy, 'packets_details': packets_details, 'live_track': live_track, 'packets_allotted': packets_allotted,})
        except KeyError:
            print("Session key not found")
    
    return redirect(reverse('BranchesInfo:branch_login_form'))


def add_delivery_boy(request):
    if request.method == "POST":
        delivery_boy_name = request.POST.get('delivery_boy_name')
        username = request.POST.get('username')
        password = request.POST.get('password')
        address = request.POST.get('address')
        contact_no = request.POST.get('contact_no')
        area = request.POST.get('area')
        branch_cd = request.POST.get('branch_cd')
        User_Type='delivery_boy'
        
        new_delivery_boy = delivery_Boy_details(
            Delivery_Boy_Name=delivery_boy_name,
            Delivery_Boy_Username=username,
            Delivery_Boy_Password=password,
            Delivery_Boy_Address=address,
            Delivery_Boy_contact_No=contact_no,
            Delivery_Boy_Area=area,
            Branch_CD=branch_cd,
            User_Type=User_Type
        )
        new_delivery_boy.save()
        messages.success(request, 'Delivery Boy Successfully.')
        
    return render(request, 'add_delivery_boy.html')  


def packet_assignment_details(request):
    if request.method == 'POST':
        form = PacketAssignmentForm(request.POST)
        if form.is_valid():
            awbno = form.cleaned_data['awbno']
            delivery_boy = form.cleaned_data['delivery_boy']
            assignment = PacketAssignmentDetails(
                Delivery_Boy_Id=delivery_boy.Delivery_Boy_Id,
                AWBNO=awbno.AWBNO,
                Assign_DT=timezone.now()
            )
            assignment.save()
            messages.success(request, 'Packet allocated successfully.')
            return redirect('BranchesInfo:branch_head_dashboard')
    else:
        form = PacketAssignmentForm()
    return render(request, 'packet_assignment_details.html', {'form': form})


def update_packet_status(request):
    delivery_boy_id = request.session.get('Delivery_Boy_Id')
    
    if request.method == 'POST':
        awbno = request.POST.get('awbno')
        transit_status = request.POST.get('transit_status')
        update_location = request.POST.get('update_location')
        order_update_time = timezone.now()

        
        delivery_boy_name = delivery_Boy_details.objects.get(Delivery_Boy_Id=delivery_boy_id).Delivery_Boy_Username

        
        orderUpdates = Live_Updates.objects.create(
            AWBNO=awbno,
            transit_status=transit_status,

courierOperationManagementSystems/BranchesInfo/templates/add_delivery_boy.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Add Delivery Boy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            text-align: center;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .form-group input[type="text"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        .form-group input[type="submit"],
        .form-group button {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 10px;

        }
        .form-group button[type="button"] {
            margin-right: 10px; 
        }
        .form-group input[type="submit"]:hover,
        .form-group button, a:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="message-section">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
          {% endif %}
    <div class="container">
        <h1>Add New Delivery Boy</h1>
        <form method="post" action="{% url 'BranchesInfo:add_delivery_boy' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="delivery_boy_name">Delivery Boy Name:</label>
                <input type="text" id="delivery_boy_name" name="delivery_boy_name" required>
            </div>
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <label for="address">Address:</label>
                <input type="text" id="address" name="address" required>
            </div>
            <div class="form-group">
                <label for="contact_no">Contact Number:</label>
                <input type="tel" id="contact_no" name="contact_no" required>
            </div>
            <div class="form-group">
                <label for="area">Area:</label>
                <input type="text" id="area" name="area">
            </div>
            <div class="form-group">
                <label for="branch_cd">Branch Code:</label>
                <input type="number" id="branch_cd" name="branch_cd" required>
            </div>
            <div class="form-group">
                <button type="submit">Add Delivery Boy</button>
                <button type="button" onclick="cancel()">Cancel</button>
                <button type="button" onclick="goToDashboard()">Go to Dashboard</button>
            </div>
        </form>
    </div>
<script 
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
</script>
<script>
    function cancel() {
        window.location.href = "{% url 'BranchesInfo:branch_head_dashboard' %}";
    }
    function goToDashboard() {
        window.location.href = "{% url 'BranchesInfo:branch_head_dashboard' %}";
    }
</script>
</body>
</html>

courierOperationManagementSystems/BranchesInfo/templates/branch_login_form.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    
    <title>Branch Login Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
                /*navbar css*/
                .nav-link:hover {
                  color: #df6b05 !important;
              }
              #services-dropdown:hover #services-menu, #login-dropdown:hover #login-menu {
                  display: block;
              }
              /*navbar css end*/
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        .login-container {
            max-width: 400px;
            margin: 100px auto;
            padding: 50px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input, .form-group select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box; /* Ensure padding is included in the width */
        }
        .form-group button {
            width: 100%; /* Make the button fill the entire width */
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
            display: block; /* Change button to display block */
        }
        .form-group button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary"
          <div class="container-fluid">
            <img src="{% static 'speedEx_logo.png' %}" alt="Logo" style="max-height: 50px; margin-right:10px;">
            <!-- Image tag on the leftmost side -->
            <!-- <a class="navbar-brand me-5 btn btn-lg" href="#" style="background-color: #FF7C00">Go To Home</a> -->
            <a class="navbar-brand me-5 btn btn-lg" href="{% url 'homeapp:home' %}" style="background-color: #FF7C00; margin-left: 9px">
              <i class="bi-house-door-fill"></i> <!-- Home icon -->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse nav justify-content-center" id="navbarNavDropdown" style="font-size: 27px;">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'userManagement:feedback'%}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homeapp:OrderTracking' %}">Order Tracking</a>
                </li>
                <!-- <li class="nav-item dropdown" id="services-dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Services
                  </a>
                  <ul class="dropdown-menu" id="services-menu" style="font-size: 27px;">
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Courier Services</a></li>
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Cargo Services</a></li>
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Logistics Services</a></li>
                  </ul>
                </li> -->
                <li class="nav-item dropdown" id="login-dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLogin" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Login
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownLogin" id="login-menu" style="font-size: 27px;">
                    <li><a class="dropdown-item" href="{% url 'userManagement:user_login_form' %}">User Login</a></li> 
                    <li><a class="dropdown-item" href="{% url 'administration:admin_login_form' %}">Admin Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'BranchesInfo:branch_login_form' %}">Branch Head Login</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <div class="message-section">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="color: red;">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
          {% endif %}
    <div class="login-container">
        <h2>Branch Login</h2>
    <form id="frmlogin" onsubmit="event.preventDefault();validate();" class="form-group"  method="POST" action="{% url 'BranchesInfo:branch_login_form' %}">
          {% csrf_token %}

            
            <div class="form-group">
                <label >Username</label>
                <input type="text" id="userid" name="userid" required>
            </div>
            <div class="form-group">
                <label >Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
              <div class="form-group">
                <label>User Type</label>
                <select id="User_Type" name="User_Type" required>
                    <option value="" disabled selected>Select User Type</option>
                    <option value="branch_head">branch_Head</option>
                    <option value="delivery_boy">delivery_boy</option>
                </select>
              </div>
                <button type="submit">Login</button>
            </div>
    </form>
    </div>
    <script>
        function validate() {
            var userid = document.getElementById("userid");
            var password = document.getElementById("password");
            if (userid.value == "" || userid.value == null) {
                alert('Please enter userid');
                userid.focus();
            } else if (password.value == "" || password.value == null) {
                alert('Please enter password');
                password.focus();
            } else {
                document.getElementById("frmlogin").submit();
            }
        }
    </script>
    <script 
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>
</body>
</html>

courierOperationManagementSystems/BranchesInfo/templates/packet_assignment_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Packet Assignment Details</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h2 class="mt-4">Packet Assignment Details</h2>
        <form action="{% url 'BranchesInfo:packet_assignment_details'%}" method="post" class="mt-4">
            {% csrf_token %}
            <div class="mb-3">
                <label for="awbno" class="form-label">Select AWBNO from drop down you want to assign:</label>
                {{ form.awbno }}
            </div>
            <div class="mb-3">
                <label for="delivery_boy" class="form-label">Select Delivery Boy from drop down you want to assign:</label>
                {{ form.delivery_boy }}
            </div>
            <button type="submit" class="btn btn-primary">Assign Packet</button>
        </form>
        <a href="{% url 'BranchesInfo:branch_head_dashboard' %}" class="btn btn-secondary mt-3">Go back to Branch Head Dashboard</a>
    </div>
    <!-- Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.bundle.min.js"></script>
</body>
</html>