courierOperationManagementSystems/BranchesInfo/urls.py
from django.urls import path
from . import views

app_name = 'BranchesInfo'
urlpatterns = [
    path('branch_login_form/', views.branch_login_form, name='branch_login_form'),
    path('branch_head_dashboard/', views.branch_head_dashboard, name='branch_head_dashboard'),
    path('delivery_boy_dashboard/', views.delivery_boy_dashboard, name='delivery_boy_dashboard'),
    path('add_delivery_boy/', views.add_delivery_boy, name='add_delivery_boy'),
    path('packet_assignment_details/', views.packet_assignment_details, name='packet_assignment_details'),
    path('delete_order/<str:awbno>/', views.delete_order, name='delete_order'),
    path('update_packet_status/', views.update_packet_status, name='update_packet_status'), 
    path('generate-qr/', views.generate_and_store_qr, name='generate_and_store_qr'),
    path('logout_view/', views.logout_view, name='logout_view'),
]

courierOperationManagementSystems/administration/urls.py
from django.urls import path, include
from . import views

app_name = 'administration'

urlpatterns = [
    path('admin_login_form/', views.admin_login_form, name='admin_login_form'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('add_branch/', views.add_branch, name='add_branch'),
    path('charge_details_view/', views.charge_details_view, name='charge_details_view'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('edit_branch/<int:branch_id>/', views.edit_branch, name='edit_branch'),
    path('delete_branch/<int:branch_id>/', views.delete_branch, name='delete_branch'),
    path('edit_charge_detail/<int:charge_id>/', views.edit_charge_detail, name='edit_charge_detail'),
    path('delete_charge_detail/<int:charge_id>/', views.delete_charge_detail, name='delete_charge_detail'),
    path('add_branch_head/', views.add_branch_head, name='add_branch_head'),
]

courierOperationManagementSystems/courierOperationManagementSystems/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'courierOperationManagementSystems'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(('homeapp.homeappurls','homeapp'), namespace='homeapp')),
    path("administration/", include(('administration.urls','administration'), namespace='administration')),
    path("userManagement/", include(('userManagement.urls','userManagement'), namespace='userManagement')),
    path("BranchesInfo/", include(('BranchesInfo.urls','BranchesInfo'), namespace='BranchesInfo')),
    path("packetTrackingSystem", include(('packetTrackingSystem.urls','packetTrackingSystem'), namespace='packetTrackingSystem')),
    path('captcha/', include('captcha.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courierOperationManagementSystems/userManagement/urls.py
from django.urls import path, include
from . import views

app_name = 'userManagement'

urlpatterns = [
    path('user_login_form/', views.user_login_form, name='user_login_form'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('signup/', views.signup, name='signup'),
    path('client_order/', views.client_order, name='client_order'),
    path('calculate-distance/', views.calculate_distance_view, name='calculate_distance'),
    path('profile/', views.profile_management, name='profile_management'),
    path('logout_view/', views.logout_view, name='logout_view'),
    path('feedback/', views.feedback, name='feedback'),
]

courierOperationManagementSystems/userManagement/models.py
from django.db import models

# Create your models here.
class Client(models.Model):
    Client_Id = models.BigAutoField(primary_key=True)
    Client_Name = models.CharField(max_length=100, null=False)
    Client_Address = models.CharField(max_length=200, null=False)
    Client_contact_No = models.CharField(max_length=15, null=True)
    Client_Email_Id = models.CharField(max_length=30, null=True, unique=True)
    def __str__(self):
        return f"{self.Client_Id} - {self.Client_Name}"


class Login_Info(models.Model):
    User_Id = models.CharField(max_length=50, null=False) # taking the email address as user id.
    User_Password = models.CharField(max_length=20, null=False)
    User_Type = models.CharField(max_length=7, null=False)
    def __str__(self):
        return self.User_Id

courierOperationManagementSystems/userManagement/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import Client
from homeapp.models import Feedback
from datetime import datetime

class MyForm(forms.Form):
    captcha = CaptchaField()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['Client_Address', 'Client_contact_No']


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['Fname', 'Lname', 'ContactNo', 'Branch_name', 'FeedbackMsg', 'Email']
        labels = {
            'Fname': 'First Name',
            'Lname': 'Last Name',
            'ContactNo': 'Your Contact Number',
            'Branch_Id': 'Branch ID',
            'Branch_name': 'Enter Branch Name',
            'FeedbackMsg': 'Enter Your Queries',
            'Email': 'Enter Your Email Address',
        }

    def save(self, commit=True):
        feedback = super().save(commit=False)
        feedback.Date = datetime.now()
        if commit:
            feedback.save()
        return feedback

courierOperationManagementSystems/userManagement/views.py
from django.shortcuts import render, redirect 
from django.urls import reverse
from . models import Client, Login_Info
from django.contrib import messages
from datetime import datetime
from django.http import HttpResponseRedirect
from . forms import MyForm, ProfileForm
from packetTrackingSystem.models import User_Info, Live_Updates
from BranchesInfo.models import Data_Records, Branches, ChargeDetails
from django.views.decorators.cache import cache_control
from django.contrib.auth import logout
from django.utils import timezone
import googlemaps
import json
from django.http import JsonResponse
from homeapp.models import Feedback
from .forms import FeedbackForm
from django.db import IntegrityError



def user_login_form(request):
    if request.method == 'POST':
        username = request.POST.get('userid')
        password = request.POST.get('password')
        try:
            login_info = Login_Info.objects.get(User_Id=username, User_Password=password)
            client = Client.objects.get(Client_Email_Id=username)
            if client.Client_Name:
                request.session['Client_Name'] = client.Client_Name
                request.session['Client_Id'] = client.Client_Id
                print("Session keys 'Client ID:' set successfully from login method: ", client.Client_Id)
                print("Session keys 'Client Name:' set successfully from login method: ", client.Client_Name)
                return redirect('userManagement:user_dashboard')
            else:
                print("Client name is empty for user:", username)
                messages.error(request, 'Client name is empty. Please contact support.')
        except Login_Info.DoesNotExist:
            print("Login failed: Invalid User name or Password")
            messages.error(request, 'Login failed: Invalid User name or Password')
    return render(request, 'user_login_form.html')


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def user_dashboard(request):
    try:
        session_id = request.session.get('Client_Id')
        username = request.session.get('Client_Name')
        if session_id is not None:
            print("Session ID of the user from dashboard function :", session_id)
            print("Session username of the user from dashboard function :", username)
            user_orders = Data_Records.objects.filter(Client_Id=session_id)
            
            
            live_updates = Live_Updates.objects.filter(AWBNO__in=[order.AWBNO for order in user_orders]).order_by('-last_update_time')
            return render(request, 'user_dashboard.html', {'user_orders': user_orders, 'username': username, 'live_updates': live_updates})
    except KeyError:
        print("Session key not found")
    
    return redirect('userManagement:user_login_form')


def signup(request):
    form=MyForm()   
    if request.method=="POST":
        form=MyForm(request.POST)
        if form.is_valid():
            Client_Name=request.POST['Client_Name']
            Client_Address=request.POST['Client_Address']
            Client_contact_No=request.POST['Client_contact_No']
            Client_Email_Id=request.POST['Client_Email_Id']
            password=request.POST['password']
            User_Type='client'
            new_client=Client(Client_Name=Client_Name, Client_Address=Client_Address, Client_contact_No=Client_contact_No, Client_Email_Id=Client_Email_Id)
            log=Login_Info( User_Id=Client_Email_Id,User_Password=password, User_Type=User_Type)
            packet_table=User_Info(User_Id=Client_Email_Id, User_Name=Client_Name, User_Address=Client_Address, User_contact_No=Client_contact_No, User_Email_Id=Client_Email_Id)
            try:
                
                new_client.save()
                log.save()
                packet_table.save()
                messages.success(request,'Client is registered')
            except IntegrityError:
                messages.error(request, 'Email address already exists. Please use a different email address.')
        else:
            messages.success(request,'Invalid captcha code')
    return render(request,"signup.html",locals())

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def client_order(request):
    client_id = request.session.get('Client_Id')
    print("Session key 'Client_Id' value:", client_id)
    
    if client_id:
        try:
            
            client = Client.objects.get(Client_Id=client_id)
        except Client.DoesNotExist:
            
            return render(request, 'User_login_form.html') 
        if request.method == 'POST':
            sender_name = request.POST['sender_name']
            sender_address = request.POST['sender_address']
            sender_contact = request.POST['sender_contact']
            order_type = request.POST['order_type']
            order_date = request.POST['order_date']
            order_time = request.POST['order_time']  
            order_datetime_str = f"{order_date}T{order_time}"
            order_date_aware = timezone.make_aware(datetime.strptime(order_datetime_str, "%Y-%m-%dT%H:%M")) 
            sender_city = request.POST['sender_city']
            sender_state = request.POST['sender_state']
            weight = request.POST['weight']
            distance = request.POST['distance']
            receiver_name = request.POST['receiver_name']
            receiver_address = request.POST['receiver_address']
            receiver_contact = request.POST['receiver_contact']
            receiver_city = request.POST['receiver_city']
            receiver_state = request.POST['receiver_state']
            payment_method = request.POST.get('payment_method')
            total_price = request.POST['total_price']
            
            if payment_method == 'card':
                #! implement the payment gateway 
                pass
            
            elif payment_method == 'netbanking':
                #! implement the payment gateway 
                pass
            
            elif payment_method == 'upi':
                #! implement the payment gateway 
                pass
            
            elif payment_method == 'cash':
                
                final_order = Data_Records(Sender_Name=sender_name, Sender_Address=sender_address, Sender_Contact_No=sender_contact, Book_date=order_date_aware, Sender_City=sender_city, Receiver_Name=receiver_name, Receiver_Address=receiver_address, Receiver_Contact_No=receiver_contact, Receiver_City=receiver_city, order_type=order_type, sender_state=sender_state, receiver_state=receiver_state, Client_Id=client, Weight=weight, Distance=distance, Price=total_price, Payment_Method=payment_method)
                final_order.save()
                return HttpResponseRedirect(reverse('userManagement:user_dashboard') + f'?username={client.Client_Name}')
        else:
            # current_date = datetime.now().strftime('%Y-%m-%d')  
            sender_states = Branches.objects.values_list('state', flat=True).distinct()
            receiver_states = Branches.objects.values_list('state', flat=True).distinct()
            sender_cities = Branches.objects.values_list('city', flat=True).distinct()
            receiver_cities = Branches.objects.values_list('city', flat=True).distinct()
            return render(request, 'client_order.html', {'sender_cities': sender_cities, 'receiver_cities': receiver_cities, 'receiver_states': receiver_states, 'sender_states': sender_states})
    else:
        
        return render(request, 'User_login_form.html')


def calculate_distance(sender_address, receiver_address, api_key):
    gmaps = googlemaps.Client(key=api_key)
    
    result = gmaps.distance_matrix(sender_address, receiver_address)
    if 'rows' in result and result['rows']:
        distance = result['rows'][0]['elements'][0]['distance']['value']
        distance_in_km = round(distance / 1000, 1)  
        return distance_in_km
    else:
        return None

def calculate_distance_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        sender_address = data.get('sender_address')
        receiver_address = data.get('receiver_address')
        api_key = ''   #! Important: Put your API key here.
        distance = calculate_distance(sender_address, receiver_address, api_key)
        if distance is not None:
            return JsonResponse({'distance': distance})
        else:
            return JsonResponse({'error': 'Failed to retrieve distance.'}, status=400)
    else:
        return JsonResponse({'error': 'Only POST requests are allowed.'}, status=405)



def calculate_price_view(request):
    if request.method == 'POST':
        weight = float(request.POST.get('weight'))
        distance_response = calculate_distance_view(request)
        if distance_response.status_code == 200:
            distance_data = distance_response.json()
            distance = distance_data.get('distance')
        else:
            return JsonResponse({'error': 'Failed to calculate distance.'}, status=400)
        charge_details = ChargeDetails.objects.filter(Weight__gte=weight).order_by('Weight').first()
        
        if charge_details:
            price_per_km = charge_details.Amount
            total_price = distance * price_per_km
            return JsonResponse({'total_price': total_price})
        else:
            return JsonResponse({'error': 'Failed to calculate price.'}, status=400)
    else:
        return JsonResponse({'error': 'Only POST requests are allowed.'}, status=405)



def profile_management(request):
    try:
        client_id = request.session.get('Client_Id')
        print(client_id)
        client = Client.objects.get(Client_Id=client_id)
        if request.method == 'POST':
            form = ProfileForm(request.POST, instance=client)
            if form.is_valid():
                form.save()
                return redirect('userManagement:user_dashboard')
        else:

courierOperationManagementSystems/userManagement/templates/manage_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manage Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        h1, h2 {
            color: #333;
        }
        form {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            color: #555;
        }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }
        button[type="submit"] {
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Manage Profile</h1>
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <h2>Profile Information</h2>
        <form method="post">
            {% csrf_token %}
            {{ profile_form.as_p }}
            <button type="submit">Update Profile</button>
        </form>

        <h2>Change Password</h2>
        <form method="post">
            {% csrf_token %}
            {{ password_form.as_p }}
            <button type="submit">Change Password</button>
        </form>
    </div>
</body>
</html>

courierOperationManagementSystems/userManagement/templates/signup.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        
        .captcha {
            font-size: 400px; 
            padding: 10px; 
            border-radius: 5px; 
            border: 1px solid #ced4da; 
        }
        .nav-link:hover {
            color: #df6b05 !important;
            }
            #services-dropdown:hover #services-menu, #login-dropdown:hover #login-menu {
            display: block;
            }
            .message-section {
              margin-top: 100px;
          }
    </style>

</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary"
            <div class="container-fluid">
            <img src="{% static 'speedEx_logo.png' %}" alt="Logo" style="max-height: 50px; margin-right:10px;">
            <!-- Image tag on the leftmost side -->
            <!-- <a class="navbar-brand me-5 btn btn-lg" href="#" style="background-color: #FF7C00">Go To Home</a> -->
            <a class="navbar-brand me-5 btn btn-lg" href="{% url 'homeapp:home' %}" style="background-color: #FF7C00; margin-left: 9px">
              <i class="bi-house-door-fill"></i> <!-- Home icon -->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse nav justify-content-center" id="navbarNavDropdown" style="font-size: 27px;">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'userManagement:feedback'%}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homeapp:OrderTracking' %}">Order Tracking</a>
                <!-- </li>
                <li class="nav-item dropdown" id="services-dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Services
                  </a>
                  <ul class="dropdown-menu" id="services-menu" style="font-size: 27px;">
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Courier Services</a></li>
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Cargo Services</a></li>
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Logistics Services</a></li>
                  </ul>
                </li> -->
                <li class="nav-item dropdown" id="login-dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLogin" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Login
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownLogin" id="login-menu" style="font-size: 27px;">
                    <li><a class="dropdown-item" href="{% url 'userManagement:user_login_form' %}">User Login</a></li> 
                    <li><a class="dropdown-item" href="{% url 'administration:admin_login_form' %}">Admin Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'BranchesInfo:branch_login_form' %}">Branch Head Login</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <div class="message-section">
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  {% endif %}
      </div>
    <div class="row justify-content-center">
        <div class="col-sm-6">
            <h2 class="text-muted" style="margin-top: 100px;">Register</h2>
            <form method="POST" action="{% url 'userManagement:signup' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label>Username:</label>
                    <input type="text" name="Client_Name" class="form-control" />
                </div><br>
                <div class="form-group">
                    <label>Home Address:</label><br>
                    <input type="text" name="Client_Address" class="form-control" />
                </div><br>
                <div class="form-group">
                    <label>Enter Your Phone Number:</label><br>
                    <input type="text" name="Client_contact_No" class="form-control" />
                </div><br>
                <div class="form-group">
                    <label>Email Address:</label><br>
                    <input type="text" name="Client_Email_Id" class="form-control" />
                </div><br>
                <div class="form-group">
                    <label>Password:</label>
                    <input type="password" name="password" class="form-control"/>
                </div><br>
                <div class="form-group">
                    <label>Re-Type Password:</label>
                    <input type="password" name="confirmpassword" class="form-control"/>
                </div><br>
                <div class="form-group">
                    <label>Type Captcha Code:</label>
                    {{ form.captcha }}
                    <!-- <input type="text" name="captcha" class="form-control"/> -->
                </div><br>
                <button type="submit" class="btn btn-dark">Submit</button>
                <a href="{% url 'userManagement:user_login_form' %}" class="btn btn-default">Login</a>
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>
</body>
</html>

courierOperationManagementSystems/userManagement/templates/user_login_form.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        /*navbar css*/
        .nav-link:hover {
            color: #df6b05 !important;
        }
        #services-dropdown:hover #services-menu, #login-dropdown:hover #login-menu {
            display: block;
        }
        /*navbar css end*/
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        .login-container {
            max-width: 400px;
            margin: 100px auto;
            padding: 50px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-group label {
            display: block;
            margin-bottom: 5px;
        }
        .form-group input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box; 
        }
        .form-group button {
            width: 100%; 
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            cursor: pointer;
            display: block; 
        }
        .form-group button:hover {
            background-color: #0056b3;
        }
        button{
            height:44px; font-size:20px
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary"
          <div class="container-fluid">
            <img src="{% static 'speedEx_logo.png' %}" alt="Logo" style="max-height: 50px; margin-right:10px;">
            <!-- Image tag on the leftmost side -->
            <!-- <a class="navbar-brand me-5 btn btn-lg" href="#" style="background-color: #FF7C00">Go To Home</a> -->
            <a class="navbar-brand me-5 btn btn-lg" href="{% url 'homeapp:home' %}" style="background-color: #FF7C00; margin-left: 9px">
              <i class="bi-house-door-fill"></i> <!-- Home icon -->
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse nav justify-content-center" id="navbarNavDropdown" style="font-size: 27px;">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'userManagement:feedback'%}">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'homeapp:OrderTracking' %}">Order Tracking</a>
                </li>
                <!-- <li class="nav-item dropdown" id="services-dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Services
                    </a>
                    <ul class="dropdown-menu" id="services-menu" style="font-size: 27px;">
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Courier Services</a></li>
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Cargo Services</a></li>
                    <li><a class="dropdown-item" href="{% url 'userManagement:client_order' %}">Logistics Services</a></li>
                    </ul>
                </li> -->
                <li class="nav-item dropdown" id="login-dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLogin" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Login
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdownLogin" id="login-menu" style="font-size: 27px;">
                    <li><a class="dropdown-item" href="{% url 'userManagement:user_login_form' %}">User Login</a></li> 
                    <li><a class="dropdown-item" href="{% url 'administration:admin_login_form' %}">Admin Login</a></li>
                    <li><a class="dropdown-item" href="{% url 'BranchesInfo:branch_login_form' %}">Branch Head Login</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <div class="login-container">
        <h2>User Login</h2>
        <form id="frmlogin" onsubmit="event.preventDefault();validate();" class="form-group"  method="POST" action="{% url 'userManagement:user_login_form' %}">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
            <div class="form-group">
                <label for="userid" style="font-size: 19px;">Username</label>
                <input type="text" id="userid" name="userid" required style="font-size: 19px;">
            </div>
            <div class="form-group">
                <label for="password" style="font-size: 19px;">Password</label>
                <input type="password" id="password" name="password" required style="font-size: 19px;">
            </div>
            <div class="form-group">
                <button type="submit">Login</button>
            </div>
            <div class="form-group">
                <button id="signupButton">Sign Up</button>
            </div>
        </form>
    </div>
    <script>
        function validate() {
            var userid = document.getElementById("userid");
            var password = document.getElementById("password");
            if (userid.value == "" || userid.value == null) {
                alert('Please enter userid');
                userid.focus();
            } else if (password.value == "" || password.value == null) {
                alert('Please enter password');
                password.focus();
            } else {
                document.getElementById("frmlogin").submit();
            }
        }
                
                document.getElementById("signupButton").addEventListener("click", function(event) {
                    event.preventDefault();
                    window.location.href = "{% url 'userManagement:signup' %}";
                });
    </script>
</body>
</html>